services:
  ollama_backend:
    container_name: 'ollama_backend'
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ollama_backend.Dockerfile
    # network_mode: none
    # ports:
    #   - 11434:11434
